feat(issue-30):implement event-card collection
Macdeal/vehikl-app pull request #31
Opened 2023-10-17 07:18 UTC by yoki1234

Closes: #30 

Developed as: 
![image](https://github.com/Macdeal/vehikl-app/assets/26956121/04c67447-3dad-4002-a1b4-e19fac325118)

2023-10-17 15:10 UTC, Macdeal commented on src/type.ts
> +}
change `EventCardProps`  to `EventCardData`

2023-10-17 15:14 UTC, Macdeal commented on src/container/EventCard.tsx
> -}
revert this, props type should be in same file

2023-10-17 15:26 UTC, Macdeal commented on src/type.ts
> +}
remove this

2023-10-17 16:47 UTC, yoki1234 commented on src/container/EventCard.tsx
> +      <EventTitle text={title} variation={variation || 'card-title'} />
explained it in Todo if any concern do let me know

2023-10-19 13:35 UTC, APJ-9 requested changes
Please check all the component variations  widths
![image](https://github.com/Macdeal/vehikl-app/assets/110293755/14e405da-d12c-4d2a-a3f9-218e36ee2200)

2023-10-20 10:02 UTC, APJ-9 approved these changes

2023-10-20 10:11 UTC, Musthaq-Ahmad approved these changes

2023-10-20 10:13 UTC, Macdeal approved these changes

2023-10-20 10:14 UTC, merged