feat: implement button component
Macdeal/vehikl-app pull request #33
Opened 2023-10-17 16:48 UTC by Macdeal

Closes - #32

2023-10-17 17:12 UTC, yoki1234 requested changes

2023-10-17 17:12 UTC, yoki1234 commented on src/components/Button/Button.tsx
> +interface ButtonProps {
is everyThing optional props,
if i am re-calling it , `text` and `onClick` are a mandatory prop.

2023-10-17 17:12 UTC, yoki1234 commented on src/components/Button/Button.tsx
> +    'rounded-lg flex align-center gap-3 px-[1rem] py-[.75rem] border-dark-orange font-semibold text-white text-center',
use provided tailwind measurements `px-[1rem]` to `px-4`, and `py-[.75rem]` to `py-3`

2023-10-17 17:12 UTC, yoki1234 commented on src/components/Button/Button.tsx
> +      [width]: true,
please do explain , why we need a style option that is always triggered?, thence it is true.

2023-10-17 17:12 UTC, yoki1234 commented on src/container/EventCard.tsx
> +import EventTitle from '../components/EventTitle/EventTitle';
do revert this change

2023-10-17 17:12 UTC, yoki1234 commented on src/components/Button/Button.tsx
> +  width: 'w-full',
why default prop is `w-full`?

2023-10-17 17:16 UTC, yoki1234 commented
Please do Attach image of what you have developed.
as `professionalism brings perfect cuts for making your future sharp.`

2023-10-18 11:26 UTC, Macdeal commented on src/container/EventCard.tsx
> +import EventTitle from '../components/EventTitle/EventTitle';
for what

2023-10-18 11:26 UTC, Macdeal commented on src/components/Button/Button.tsx
> +  width: 'w-full',
then what would be the default value

2023-10-20 10:58 UTC, merged